world:
  overview: 中世ヨーロッパ風ファンタジー世界

character:
  - name: アクト
    role: 主人公
    description:
      - 旅をしている
      - 最強の魔法使いで最強の剣士

  - name: メグ
    role: ヒロイン
    description:
      - 主人公と一緒に旅をしている
      - 剣士
